
export const LoginConstants = {
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',
  USER_IS_LOGGING_IN: 'USER_IS_LOGGING_IN',
};

export const UserDataConstants = {
  VIEW_USER_DATA_SUCCESS: 'VIEW_USER_DATA_SUCCESS',
  VIEW_USER_DATA_FAIL: 'VIEW_USER_DATA_FAIL',
};

export const EditAddressConstants = {
  EDIT_ADDRESS_SUCCESS: 'EDIT_ADDRESS_SUCCESS',
  EDIT_ADDRESS_FAIL: 'EDIT_ADDRESS_FAIL',
};
